name: Update Brussels data

on:
  # Run every Monday at 1:00 UTC
  schedule:
    - cron: "0 1 * * 1"
  push:
    paths:
      - ".github/workflows/update-brussels.yml"
      - "cities/brussels/config.php"
      - "cities/brussels/overpass/*"
  pull_request:
    paths:
      - ".github/workflows/update-brussels.yml"
      - "cities/brussels/config.php"
      - "cities/brussels/overpass/*"

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true
      - name: Use PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: curl, pdo, sqlite3
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Checkout submodule to master
        working-directory: cities/brussels
        run: git checkout -q master
      - name: Update sub-modules
        run: git submodule update --remote --merge cities/brussels

      - name: Run update
        run: composer run update-data -- --city=brussels

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Brussels
          path: cities/brussels/data/*

      - name: Commit sub-module
        if: ${{ github.event_name != 'pull_request' }}
        working-directory: cities/brussels
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add data/*
          git commit -m "ðŸ—ƒ Update data"
      - name: Push to sub-module
        uses: ad-m/github-push-action@master
        if: ${{ github.event_name != 'pull_request' }}
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          directory: cities/brussels
          repository: openknowledgebe/equalstreetnames-brussels
      - name: Commit repository
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git pull
          git add cities/brussels
          git commit -m "ðŸ—ƒ Update Brussels sub-module"
      - name: Push to repository
        uses: ad-m/github-push-action@master
        if: ${{ github.event_name != 'pull_request' }}
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
